### PR TITLE
Use standard JSON library instead of yajl

### PR DESCRIPTION
**Pull request by perlun**
yajl-ruby has the downside that is relies on a C extension which works poorly (well, not at all...) with JRuby. We are targetting JRuby in our main project using this gem, so this change is mandatory for us to be able to use it.

I've tested this locally and it seems to stream changes fine. However, it's only been tested with very small amounts of data as of yet.

## Performance impact

With this change in place, running towards a reasonably complex table on MRI 2.4.1 - **46** seconds:

```
$ bundle exec bin/couch_tap test_tap.rb
I, [2017-05-16T11:07:26.753914 #26627]  INFO -- : Reading configuration: test_tap.rb
I, [2017-05-16T11:07:26.765091 #26627]  INFO -- : Connected to CouchDB: fieldops_equipment
I, [2017-05-16T11:07:26.800341 #26627]  INFO -- : fieldops_equipment: listening to changes feed from seq: 0
I, [2017-05-16T11:07:30.526633 #26627]  INFO -- : Processed 1000 rows
I, [2017-05-16T11:07:34.417928 #26627]  INFO -- : Processed 2000 rows
I, [2017-05-16T11:07:38.540526 #26627]  INFO -- : Processed 3000 rows
I, [2017-05-16T11:07:42.936004 #26627]  INFO -- : Processed 4000 rows
I, [2017-05-16T11:07:47.630417 #26627]  INFO -- : Processed 5000 rows
I, [2017-05-16T11:07:51.953686 #26627]  INFO -- : Processed 6000 rows
I, [2017-05-16T11:07:56.889749 #26627]  INFO -- : Processed 7000 rows
I, [2017-05-16T11:08:02.297558 #26627]  INFO -- : Processed 8000 rows
I, [2017-05-16T11:08:07.253657 #26627]  INFO -- : Processed 9000 rows
I, [2017-05-16T11:08:12.562975 #26627]  INFO -- : Processed 10000 rows
```

Running the same code on JRuby 9.1.8 takes about **81** seconds. Slower but still not completely unreasonable:

```
$ bundle exec bin/couch_tap test_tap.rb
I, [2017-05-16T11:12:00.388765 #27463]  INFO -- : Reading configuration: test_tap.rb
I, [2017-05-16T11:12:00.439899 #27463]  INFO -- : Connected to CouchDB: fieldops_equipment
I, [2017-05-16T11:12:00.657477 #27463]  INFO -- : fieldops_equipment: listening to changes feed from seq: 0
I, [2017-05-16T11:12:08.830354 #27463]  INFO -- : Processed 1000 rows
I, [2017-05-16T11:12:16.910913 #27463]  INFO -- : Processed 2000 rows
I, [2017-05-16T11:12:24.780557 #27463]  INFO -- : Processed 3000 rows
I, [2017-05-16T11:12:32.923519 #27463]  INFO -- : Processed 4000 rows
I, [2017-05-16T11:12:41.896976 #27463]  INFO -- : Processed 5000 rows
I, [2017-05-16T11:12:50.102341 #27463]  INFO -- : Processed 6000 rows
I, [2017-05-16T11:12:58.137898 #27463]  INFO -- : Processed 7000 rows
I, [2017-05-16T11:13:05.830220 #27463]  INFO -- : Processed 8000 rows
I, [2017-05-16T11:13:13.489721 #27463]  INFO -- : Processed 9000 rows
I, [2017-05-16T11:13:21.202113 #27463]  INFO -- : Processed 10000 rows
```

With the original code - **42** seconds. Definitely the fastest approach, but still only 10% faster than the non-streaming version on MRI.

```
$ bundle exec bin/couch_tap test_tap.rb
I, [2017-05-16T11:15:55.031116 #28182]  INFO -- : Reading configuration: test_tap.rb
I, [2017-05-16T11:15:55.040127 #28182]  INFO -- : Connected to CouchDB: fieldops_equipment
I, [2017-05-16T11:15:55.077931 #28182]  INFO -- : fieldops_equipment: listening to changes feed from seq: 0
I, [2017-05-16T11:15:58.994339 #28182]  INFO -- : Processed 1000 rows
I, [2017-05-16T11:16:03.001351 #28182]  INFO -- : Processed 2000 rows
I, [2017-05-16T11:16:07.237647 #28182]  INFO -- : Processed 3000 rows
I, [2017-05-16T11:16:11.723076 #28182]  INFO -- : Processed 4000 rows
I, [2017-05-16T11:16:16.834998 #28182]  INFO -- : Processed 5000 rows
I, [2017-05-16T11:16:21.063894 #28182]  INFO -- : Processed 6000 rows
I, [2017-05-16T11:16:25.308424 #28182]  INFO -- : Processed 7000 rows
I, [2017-05-16T11:16:29.417598 #28182]  INFO -- : Processed 8000 rows
I, [2017-05-16T11:16:33.673768 #28182]  INFO -- : Processed 9000 rows
I, [2017-05-16T11:16:37.926714 #28182]  INFO -- : Processed 10000 rows
```

### CODE REVIEW

**Review by afinne — APPROVED** [review]
Looks good, but it would be really nice if you could test it with, say the equipment db, and just compare the performance between the implementations.

**Comment by perlun** [comment]
> Looks good, but it would be really nice if you could test it with, say the equipment db, and just compare the performance between the implementations.

I added the performance impact now. Are you still fine with the change after seeing these numbers?

**Comment by afinne** [comment]
👍

**Comment by perlun** [comment]
Thanks!

**Pull request merged**
